### ISSUE TITLE
[dbus-stream] 分库分表配置table时，增量不支持表正则，仅模板表有增量数据

### ISSUE THREAD

**Issue by wupan-olo** [BriData/DBus#31]
#### 背景：
  一个database,mydb下有1024个表 share_\d+
  将share_0作为模板表，配置表正则为share_\d+

#### 问题：
  增量时，仅有share_0存在增量数据，其余表数据均被静默过滤

**Comment by star-brilliant** [comment]
模板表仅仅提供输出namespace名称和表meta信息，正则才是真正的数据映射，你可以改为配置share_.*

**Comment by wupan-olo** [comment]
嗯，不管那种则正表达模式，都是为了让物理的分表能带上模版表的meta信息，后面的拓扑能正确处理。
这个tableMatchContainer存储的是 模版(table_name) -> 正则(physical_table_regex)
当执行TableMatchContainer.getInstance().getLocalTable(tableName);时
例如：
   存储的是 t_a_0 -> t_a_\d+
                   t_b  ->  t_b
当前fetch的table_name = t_a_100;
```java
public String getLocalTable(String table){
		for(Map.Entry<String, String> entry : map.entrySet()){
			if(!table.contains(entry.getKey()))
				continue;
			if(table.matches(entry.getValue())){
				return entry.getKey();
			}
		}
		return table;
	}
```
这样执行返回的table_name不是期望的模版表名称。结果就是直接被filter掉了。

**我提交的第一个pr里面我没有仔细看到mysql-extractor的实现，后面发现其实你们已经充分考虑到了分表的增量处理，只是在上诉方法中存在一个逻辑bug**
