### ISSUE TITLE
编译报错-Error adding file to archive: /home/DBus-0.6.1/deployer/../canal.zip isn't a file

### ISSUE THREAD

**Issue by JohnBarrowman65** [BriData/DBus#56]
![image](https://user-images.githubusercontent.com/30208746/80356881-b32c5180-88ac-11ea-8c69-dc189483f954.png)
如图，you有大佬解答下吗？

**Comment by JohnBarrowman65** [comment]
no body？

**Comment by lihhj** [comment]
也碰到这个问题了，请问解决了吗？谢谢

**Comment by JohnBarrowman65** [comment]
> 也碰到这个问题了，请问解决了吗？谢谢

解决了，把最后两个注释掉就行了，后面去他网盘里面找到对应的canal.zip和build.zip手动重新弄进去就好了
